import { Answer } from '../types';
import { ALL_QUESTIONS, HAX_STAGES } from '../data/haxData';

const HAX_TOOLKIT_URL = 'https://www.microsoft.com/en-us/haxtoolkit/';
const HAX_LIBRARY_URL = 'https://www.microsoft.com/en-us/haxtoolkit/library/';

export function generatePrompt(answers: Answer[]): string {
  const enabledAnswers = answers.filter((a) => a.enabled);

  const timestamp = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  if (enabledAnswers.length === 0) {
    return `# 🎯 Vibe Coding Plan — HAX Compliance Blueprint

> **Generated:** ${timestamp}
> **Framework:** [Microsoft HAX Toolkit](${HAX_TOOLKIT_URL}) — Human-AI eXperience Guidelines

---

No HAX guidelines were selected. This plan serves as a reminder to revisit the questionnaire and specify how your AI application will handle each human-interaction pattern.

**Recommended next step:** Return to the questionnaire and toggle "Yes" for any guidelines relevant to your app, then add your implementation notes.

Reference: [HAX Toolkit Library — All 18 Guidelines](${HAX_LIBRARY_URL})
`;
  }

  const checklist = enabledAnswers
    .map((a) => {
      const q = ALL_QUESTIONS.find((q) => q.id === a.questionId);
      return q
        ? `- [ ] **${q.guideline}** — ${q.guidelineTitle} ([source](${q.guidelineUrl}))`
        : '';
    })
    .filter(Boolean)
    .join('\n');

  const stageSections = HAX_STAGES.map((stage) => {
    const stageQAs = stage.questions
      .map((q) => {
        const answer = answers.find((a) => a.questionId === q.id);
        if (!answer || !answer.enabled) return null;
        return { question: q, answer };
      })
      .filter(Boolean) as { question: (typeof ALL_QUESTIONS)[0]; answer: Answer }[];

    if (stageQAs.length === 0) return null;

    const questionBlocks = stageQAs
      .map(
        ({ question, answer }) => `#### ${question.guideline}: ${question.guidelineTitle}

> *Source: [HAX Toolkit Library – ${question.guideline}](${question.guidelineUrl})*

**Scenario:** ${question.question}

**Implementation Plan:**
${answer.note?.trim() || '_No specific implementation notes provided. Apply HAX best-practice patterns for this guideline._'}
`
      )
      .join('\n');

    return `### ${stage.label}: ${stage.description}

${questionBlocks}`;
  })
    .filter(Boolean)
    .join('\n---\n\n');

  return `# 🎯 Vibe Coding Plan — HAX Compliance Blueprint

> **Generated:** ${timestamp}
> **Framework:** [Microsoft HAX Toolkit](${HAX_TOOLKIT_URL}) — Human-AI eXperience Guidelines
> **Full guidelines library:** [All 18 HAX Guidelines](${HAX_LIBRARY_URL})

---

## How to Use This Plan

Paste this document into your AI coding agent's **plan mode** (e.g., Cursor, Claude, Copilot, ChatGPT). It translates Microsoft's HAX Toolkit guidelines into concrete UI/UX requirements for your AI-powered application.

> ⚠️ **Important Note:** This plan describes *interaction design patterns* your AI feature must implement. It does **not** write code for you — the resulting implementation will require engineering effort and may need manual tweaking to fit your specific tech stack, framework, and use cases.

---

## HAX Compliance Checklist

${checklist}

---

## Detailed Implementation Plan

${stageSections}

---

## Instructions for Your AI Coding Agent

> You are implementing an AI-powered feature that must comply with Microsoft's Human-AI eXperience (HAX) Toolkit guidelines (${HAX_LIBRARY_URL}). The sections above describe each required guideline and the product owner's intended implementation approach. Follow these instructions:
>
> 1. **UI Requirements**: Add all required UI elements (buttons, labels, tooltips, status indicators, confidence badges, dismissal controls) as described in each guideline section above.
> 2. **State Management**: Implement the state management needed to support undo/redo actions, interaction history, and user preference memory where specified.
> 3. **Error Handling**: Ensure errors and AI mistakes surface clearly to the user with actionable, human-friendly recovery options — never fail silently.
> 4. **Bias Mitigation**: Where specified, add content filtering, diverse example sets, and user feedback mechanisms to surface potential biases.
> 5. **Testing**: Validate each HAX interaction pattern against real user scenarios before marking the feature complete.
>
> **Reference:**
> - [Microsoft HAX Toolkit Overview](${HAX_TOOLKIT_URL})
> - [All 18 HAX Guidelines with Examples and Sample Patterns](${HAX_LIBRARY_URL})

---

*Generated by HAX Vibe Coding Plan Generator — powered by the [Microsoft HAX Toolkit](${HAX_TOOLKIT_URL})*
`;
}
